CC = gcc
LIB = -lpthread -lisal -lm
BINCLIENT = client
BINSERVER = server
EXECUTABLECLIENT = ${BINCLIENT}/client
EXECUTABLESERVER = ${BINSERVER}/server

all:	client server

client:	myftp.c ${BINCLIENT}/myftpclient.c
	${CC} $^ -o ${EXECUTABLECLIENT} ${LIB}

server:	myftp.c ${BINSERVER}/myftpserver.c
	${CC} $^ -o ${EXECUTABLESERVER} ${LIB}

